# Generated by Django 4.1.3 on 2022-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_employe', models.CharField(max_length=200)),
                ('pseudo_employe', models.CharField(max_length=200)),
                ('password_employe', models.CharField(max_length=200)),
                ('specialite_employe', models.CharField(max_length=200)),
                ('description_employe', models.CharField(max_length=200)),
                ('statu_employe', models.BooleanField()),
            ],
        ),
    ]
