# Generated by Django 4.1.3 on 2022-11-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='statu_employe',
            field=models.BooleanField(default=False),
        ),
    ]
