# Generated by Django 4.1.3 on 2022-11-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employe_statu_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='statu_employe',
        ),
    ]
