# Generated by Django 4.1.3 on 2022-11-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employe_statu_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image_employe',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
