# Generated by Django 4.1.3 on 2022-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employe_image_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='support_divinatoire_employe',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
