# Generated by Django 4.1.3 on 2022-11-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employe_support_divinatoire_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='support_divinatoire_employe',
            field=models.CharField(max_length=200),
        ),
    ]
