# Generated by Django 4.1.3 on 2022-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employe_support_divinatoire_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='image_employe',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
