# Generated by Django 4.1.3 on 2022-12-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_minutes', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
