# Generated by Django 4.1.3 on 2022-12-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_utilisateur_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='statu_employe',
            new_name='statut_employe',
        ),
    ]
