# Generated by Django 4.1.3 on 2022-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_statu_employe_employe_statut_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nbr_min',
            field=models.IntegerField(default=0),
        ),
    ]
