# Generated by Django 4.1.3 on 2023-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_historiqueinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationi', models.CharField(default=None, max_length=200)),
                ('sender', models.CharField(default=None, max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
